version: "3"

services:
  server-dev:
    image: clarksam19/fullstack-init_server:dev
    build: ./server
    ports:
      - 3001:3001
    volumes:
      - ./server:/usr/src/app/local
      - ./client/build:/usr/src/app/local/build
    container_name: test-server
    environment:
      - PORT=3001
    env_file:
      - ./.env
  client:
    image: clarksam19/react-client:dev
    ports:
      - 3000:3000
    volumes:
      - ./client:/usr/src/app/local
      - node_modules_client:/usr/src/app/local/node_modules
    container_name: test-client
    environment:
      - PORT=3000
  db-test:
    image: mongo
    restart: always
    container_name: db-test
    ports:
      - 27017:27017
    volumes:
      - db-test:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=db-test
  db-test-admin:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=db-test
    container_name: db-test-admin
    ports:
      - 8081:8081
volumes:
  node_modules_client:
  db-test:
