version: "3"

services:
  server-prod:
    image: clarksam19/fullstack-init_server:prod
    build: .
    ports:
      - 8000:8000
    container_name: test-server-prod
    environment:
      - PORT=8000
    env_file:
      - ./.env
