POST http://localhost:3001/api/users HTTP/1.1
Content-Type: application/json

{
  "contents": [],
  "username": "test",
  "name": "test user",
  "password": "testpassword"
}

### 

GET http://localhost:3001/api/temp/ HTTP/1.1

###

POST http://localhost:3001/api/login HTTP/1.1
Content-Type: application/json

{
  "username": "test",
  "password": "testpassword"
}

###

POST http://localhost:3001/api/temp HTTP/1.1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxMDFkYzhkY2Q0NzZlMDAyMThmMjNiYSIsImlhdCI6MTYyNzUxMTk3OSwiZXhwIjoxNjI3NTE1NTc5fQ.zXLBnUwohGcB0kvyh8h8_-UoyVDpwg-uTu_QmhoM1P0

{
  "content": "token authorized content"
}
###

DELETE http://localhost:3001/api/temp/6101605a689c7c016c622b9c HTTP/1.1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjYxMDFkYzhkY2Q0NzZlMDAyMThmMjNiYSIsImlhdCI6MTYyNzUxMTk3OSwiZXhwIjoxNjI3NTE1NTc5fQ.zXLBnUwohGcB0kvyh8h8_-UoyVDpwg-uTu_QmhoM1P0
###

GET http://localhost:3001/api/temp HTTP/1.1


